import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/navbar";
import Hero from "@/components/hero";
import CardItinerary from "@/components/cardItinerary";
import {itineraryData} from "@/mock/data"
import Footer from "@/components/footer.jsx";
import { useState } from "react";



export default function Home() {
  const [showMore, setShowMore] = useState(false); 
  const maxVisibleItineraries = 8;

  const handleToggleShowMore = () => {
    setShowMore((ShowMore) => !ShowMore);
  };
 
  return (
    <>
      <Head>
        <title>{}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        {/* ------------ NAVBAR ------------ */}
      <Navbar/>
      {/* ------------ HERO ------------ */}
      <Hero/>
      <div className={styles.container}>
      <div className={styles.cardContainer}>
      {itineraryData.slice(0,  showMore ? itineraryData.length : maxVisibleItineraries).map((itinerary) => (
        <CardItinerary key={itinerary.id} itinerary={itinerary} />
      ))}
      </div>
      <div className={styles.buttonContainer}>
      <button className={styles.showMoreButton} onClick={handleToggleShowMore}>
        {showMore ? 'Show Less' : 'Show More'}
      </button>
      </div>
      </div>
      <Footer/>
      </main>
    </>
  );
}
